version: '3.7'
services:
  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - DEBUG=1
    volumes:
      - "parse-db-data:/data/db"
      - "parse-db-data:/data/configdb"
  parse-server:
    image: parseplatform/parse-server:3.9.0
    ports:
      - "8080:1337"
    networks:
      - backend
      - frontend
    environment:
      - PARSE_SERVER_APPLICATION_ID=appid
      - PARSE_SERVER_MASTER_KEY=masterkey
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo/test
      - PARSE_SERVER_CLIENT_KEY=clientKey
      - PARSE_SERVER_JAVASCRIPT_KEY=javascriptKey
      - PARSE_SERVER_REST_API_KEY=restAPIKey
      - PARSE_SERVER_LIVE_QUERY={"classNames":["BME280","BME680","BMP085","BMP280","Device","Error"]}
      # - PORT=1337
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_MOUNT_GRAPHQL=1
      - PARSE_SERVER_MOUNT_PLAYGROUND=1
      #- PARSE_SERVER_CLOUD='/colud/main.js'
    depends_on:
      - mongo
  parse-dashboard:
    image: parseplatform/parse-dashboard:2.0.3
    networks:
      - frontend
    ports:
      - "8081:4040"
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    volumes:
      - //Users/kila/desktop/docker/docker-parse-server-develop/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json

networks:
  frontend:
  backend:

volumes:
  parse-db-data: