USER1=kila \
USER1_PASSWORD=kila2l \
APP_ID=appid \
MASTER_KEY=masterkey \
REST_API_KEY=restapikey \
CLIENT_KEY=clientkey \
ALLOW_CLIENT_CLASS_CREATION=1 \
PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1 \
SERVER_URL=http://localhost:1337/parse \
LIVEQUERY_SUPPORT=true \
LIVEQUERY_CLASSES=User,People \
GRAPHQL_SUPPORT=true \
docker-compose up -d
