version: "3.7"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok:
    container_name: opengrok
    image: opengrok/docker:latest
    ports:
      - "8082:8080/tcp"
    environment:
      REINDEX: '60'
    # Volumes store your data between container upgrades
    volumes:
       - 'opengork-src:/opengrok/src/'  # source code
       - 'opengork-etc:/opengrok/etc/'  # folder contains configuration.xml
       - 'opengork-data:/opengrok/data'  # index and other things for source code
volumes:
  opengork-src:
  opengork-etc:
  opengork-data:
