version: '3.7'
services:
  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - DEBUG=1
    volumes:
      - "common-db-data:/data/db"
      - "common-db-data:/data/configdb"
networks:
  backend:

volumes:
  common-db-data:
